name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependencies and Run Tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        make check 
    - name: Check Coverage and Generate Report 
      run: | 
        coverage report --fail-under=100 
        coverage html --omit="*/tests/*" # omit tests from coverage report
    - name: Save Coverage Report 
      uses: actions/upload-artifact@v2 
      with: 
        name: coverage-report 
        path: htmlcov

